
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  simple-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Test and Build
        run: |
          npm install
          npm test
          npm run build --if-present
          rm -rf node_modules

      - name : Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: latest-artifact
            path: |
              .
    
      - name : Download Artifact
        uses: actions/download-artifact@v4
        with:
            name: latest-artifact
    
      - name: Copy to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.EC2_INSTANCE_IP }}
            username: ubuntu
            key: ${{ secrets.SSH_KEY }}
            port: 22
            source: ./
            target: ~/git_hub_actions_ci_cd

      - name: Start Web App
        uses: appleboy/ssh-action@v1.2.1
        with:
            host: ${{ secrets.EC2_INSTANCE_IP }}
            username: ubuntu
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script: |
                export NVM_DIR=~/.nvm
                source ~/.nvm/nvm.sh
                cd ~/git_hub_actions_ci_cd
                npm install
                npm run start     